name: test
on: workflow_dispatch
jobs:
  test-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Echoing a statement
        run: echo "testing started"
      - name: echoing finish statement
        run: echo "Finished"
